-- Check which regions have data
SELECT 
    reg.RESPONDENT,
    COUNT(*) as record_count
FROM USER_DB_HIPPO.ELECTRICITY_ANALYTICS.FCT_HOURLY_DEMAND fct
JOIN USER_DB_HIPPO.ELECTRICITY_ANALYTICS.DIM_REGION reg
    ON fct.REGION_KEY = reg.REGION_KEY
GROUP BY reg.RESPONDENT
ORDER BY record_count DESC;

-- Check which regions have forecasts
SELECT 
    REGION,
    COUNT(*) as forecast_count
FROM USER_DB_HIPPO.ELECTRICITY_ML.FORECAST_RESULTS
GROUP BY REGION
ORDER BY REGION;
