-- ============================================
-- Snowflake Schema Setup for Electricity Forecasting Project
-- SJSU Data Engineering - Complete Database Structure
-- ============================================

USE DATABASE USER_DB_HIPPO;

-- ============================================
-- SCHEMA 1: ELECTRICITY_RAW (Landing Zone)
-- ============================================
CREATE SCHEMA IF NOT EXISTS ELECTRICITY_RAW;

-- Main table for EIA hourly demand data
CREATE TABLE IF NOT EXISTS ELECTRICITY_RAW.EIA_HOURLY_DEMAND (
    PERIOD_DATE TIMESTAMP NOT NULL,
    RESPONDENT VARCHAR(50) NOT NULL,
    RESPONDENT_NAME VARCHAR(255),
    DATA_TYPE VARCHAR(20) NOT NULL,
    DATA_TYPE_NAME VARCHAR(255),
    VALUE FLOAT,
    VALUE_UNITS VARCHAR(50),
    LOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (PERIOD_DATE, RESPONDENT, DATA_TYPE)
);

-- Temp table for staging (used during ETL)
CREATE TABLE IF NOT EXISTS ELECTRICITY_RAW.EIA_HOURLY_DEMAND_TEMP (
    PERIOD_DATE TIMESTAMP NOT NULL,
    RESPONDENT VARCHAR(50) NOT NULL,
    RESPONDENT_NAME VARCHAR(255),
    DATA_TYPE VARCHAR(20) NOT NULL,
    DATA_TYPE_NAME VARCHAR(255),
    VALUE FLOAT,
    VALUE_UNITS VARCHAR(50)
);

-- ============================================
-- SCHEMA 2: ELECTRICITY_STAGING (Cleaned Data)
-- ============================================
CREATE SCHEMA IF NOT EXISTS ELECTRICITY_STAGING;

-- Staging table for cleaned EIA data
CREATE TABLE IF NOT EXISTS ELECTRICITY_STAGING.STG_EIA_HOURLY_DEMAND (
    PERIOD_DATE TIMESTAMP NOT NULL,
    RESPONDENT VARCHAR(50) NOT NULL,
    RESPONDENT_NAME VARCHAR(255),
    DATA_TYPE VARCHAR(20) NOT NULL,
    DATA_TYPE_NAME VARCHAR(255),
    VALUE FLOAT,
    VALUE_UNITS VARCHAR(50),
    LOADED_AT TIMESTAMP,
    PRIMARY KEY (PERIOD_DATE, RESPONDENT, DATA_TYPE)
);

-- Aggregated demand by region
CREATE TABLE IF NOT EXISTS ELECTRICITY_STAGING.STG_DEMAND_BY_REGION (
    PERIOD_DATE TIMESTAMP NOT NULL,
    RESPONDENT VARCHAR(50) NOT NULL,
    RESPONDENT_NAME VARCHAR(255),
    TOTAL_DEMAND FLOAT,
    AVG_DEMAND FLOAT,
    MAX_DEMAND FLOAT,
    MIN_DEMAND FLOAT,
    RECORD_COUNT INT,
    PRIMARY KEY (PERIOD_DATE, RESPONDENT)
);

-- ============================================
-- SCHEMA 3: ELECTRICITY_ANALYTICS (Data Marts)
-- ============================================
CREATE SCHEMA IF NOT EXISTS ELECTRICITY_ANALYTICS;

-- Dimension: Region
CREATE TABLE IF NOT EXISTS ELECTRICITY_ANALYTICS.DIM_REGION (
    REGION_KEY INT AUTOINCREMENT PRIMARY KEY,
    RESPONDENT VARCHAR(50) UNIQUE NOT NULL,
    RESPONDENT_NAME VARCHAR(255),
    REGION_TYPE VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Dimension: Date
CREATE TABLE IF NOT EXISTS ELECTRICITY_ANALYTICS.DIM_DATE (
    DATE_KEY INT PRIMARY KEY,
    DATE_VALUE DATE NOT NULL,
    YEAR INT,
    QUARTER INT,
    MONTH INT,
    MONTH_NAME VARCHAR(20),
    WEEK INT,
    DAY INT,
    DAY_OF_WEEK INT,
    DAY_NAME VARCHAR(20),
    IS_WEEKEND BOOLEAN,
    IS_HOLIDAY BOOLEAN
);

-- Fact: Hourly Demand
CREATE TABLE IF NOT EXISTS ELECTRICITY_ANALYTICS.FCT_HOURLY_DEMAND (
    DEMAND_KEY INT AUTOINCREMENT PRIMARY KEY,
    PERIOD_DATE TIMESTAMP NOT NULL,
    DATE_KEY INT,
    REGION_KEY INT,
    HOUR INT,
    DEMAND_VALUE FLOAT,
    DEMAND_UNITS VARCHAR(50),
    LOADED_AT TIMESTAMP,
    FOREIGN KEY (REGION_KEY) REFERENCES ELECTRICITY_ANALYTICS.DIM_REGION(REGION_KEY),
    FOREIGN KEY (DATE_KEY) REFERENCES ELECTRICITY_ANALYTICS.DIM_DATE(DATE_KEY)
);

-- Analytics Summary Table
CREATE TABLE IF NOT EXISTS ELECTRICITY_ANALYTICS.ANALYTICS_DEMAND_SUMMARY (
    SUMMARY_KEY INT AUTOINCREMENT PRIMARY KEY,
    PERIOD_DATE TIMESTAMP NOT NULL,
    REGION VARCHAR(50),
    HOUR INT,
    DAY_OF_WEEK INT,
    TOTAL_DEMAND FLOAT,
    AVG_DEMAND FLOAT,
    MAX_DEMAND FLOAT,
    MIN_DEMAND FLOAT,
    DEMAND_VARIANCE FLOAT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================
-- SCHEMA 4: ELECTRICITY_ML (Machine Learning)
-- ============================================
CREATE SCHEMA IF NOT EXISTS ELECTRICITY_ML;

-- ML Forecast Results
CREATE TABLE IF NOT EXISTS ELECTRICITY_ML.FORECAST_RESULTS (
    FORECAST_KEY INT AUTOINCREMENT PRIMARY KEY,
    FORECAST_DATE TIMESTAMP NOT NULL,
    REGION VARCHAR(50) NOT NULL,
    FORECAST_HORIZON INT,  -- Hours ahead (1-24)
    PREDICTED_DEMAND FLOAT,
    ACTUAL_DEMAND FLOAT,
    PREDICTION_ERROR FLOAT,
    MODEL_VERSION VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Model Performance Metrics
CREATE TABLE IF NOT EXISTS ELECTRICITY_ML.MODEL_METRICS (
    METRIC_KEY INT AUTOINCREMENT PRIMARY KEY,
    MODEL_VERSION VARCHAR(50) NOT NULL,
    TRAINING_DATE TIMESTAMP NOT NULL,
    REGION VARCHAR(50),
    METRIC_NAME VARCHAR(50),  -- R2, RMSE, MAE, MAPE
    METRIC_VALUE FLOAT,
    DATASET_TYPE VARCHAR(20),  -- train, test, validation
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Feature Importance
CREATE TABLE IF NOT EXISTS ELECTRICITY_ML.FEATURE_IMPORTANCE (
    FEATURE_KEY INT AUTOINCREMENT PRIMARY KEY,
    MODEL_VERSION VARCHAR(50) NOT NULL,
    FEATURE_NAME VARCHAR(100),
    IMPORTANCE_SCORE FLOAT,
    RANK INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================
-- Initial Data: Populate DIM_REGION
-- ============================================
INSERT INTO ELECTRICITY_ANALYTICS.DIM_REGION (RESPONDENT, RESPONDENT_NAME, REGION_TYPE)
SELECT DISTINCT 
    'US48' AS RESPONDENT,
    'United States Lower 48' AS RESPONDENT_NAME,
    'National' AS REGION_TYPE
WHERE NOT EXISTS (SELECT 1 FROM ELECTRICITY_ANALYTICS.DIM_REGION WHERE RESPONDENT = 'US48');

INSERT INTO ELECTRICITY_ANALYTICS.DIM_REGION (RESPONDENT, RESPONDENT_NAME, REGION_TYPE)
SELECT DISTINCT 
    'CISO' AS RESPONDENT,
    'California Independent System Operator' AS RESPONDENT_NAME,
    'Regional' AS REGION_TYPE
WHERE NOT EXISTS (SELECT 1 FROM ELECTRICITY_ANALYTICS.DIM_REGION WHERE RESPONDENT = 'CISO');

INSERT INTO ELECTRICITY_ANALYTICS.DIM_REGION (RESPONDENT, RESPONDENT_NAME, REGION_TYPE)
SELECT DISTINCT 
    'TEXA' AS RESPONDENT,
    'Electric Reliability Council of Texas' AS RESPONDENT_NAME,
    'Regional' AS REGION_TYPE
WHERE NOT EXISTS (SELECT 1 FROM ELECTRICITY_ANALYTICS.DIM_REGION WHERE RESPONDENT = 'TEXA');

INSERT INTO ELECTRICITY_ANALYTICS.DIM_REGION (RESPONDENT, RESPONDENT_NAME, REGION_TYPE)
SELECT DISTINCT 
    'MISO' AS RESPONDENT,
    'Midcontinent Independent System Operator' AS RESPONDENT_NAME,
    'Regional' AS REGION_TYPE
WHERE NOT EXISTS (SELECT 1 FROM ELECTRICITY_ANALYTICS.DIM_REGION WHERE RESPONDENT = 'MISO');

INSERT INTO ELECTRICITY_ANALYTICS.DIM_REGION (RESPONDENT, RESPONDENT_NAME, REGION_TYPE)
SELECT DISTINCT 
    'NYISO' AS RESPONDENT,
    'New York Independent System Operator' AS RESPONDENT_NAME,
    'Regional' AS REGION_TYPE
WHERE NOT EXISTS (SELECT 1 FROM ELECTRICITY_ANALYTICS.DIM_REGION WHERE RESPONDENT = 'NYISO');

INSERT INTO ELECTRICITY_ANALYTICS.DIM_REGION (RESPONDENT, RESPONDENT_NAME, REGION_TYPE)
SELECT DISTINCT 
    'PJM' AS RESPONDENT,
    'PJM Interconnection' AS RESPONDENT_NAME,
    'Regional' AS REGION_TYPE
WHERE NOT EXISTS (SELECT 1 FROM ELECTRICITY_ANALYTICS.DIM_REGION WHERE RESPONDENT = 'PJM');

-- ============================================
-- Initial Data: Populate DIM_DATE (2023-2026)
-- ============================================
CREATE OR REPLACE PROCEDURE ELECTRICITY_ANALYTICS.POPULATE_DIM_DATE()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    -- Generate dates from 2023-01-01 to 2026-12-31
    INSERT INTO ELECTRICITY_ANALYTICS.DIM_DATE (
        DATE_KEY, DATE_VALUE, YEAR, QUARTER, MONTH, MONTH_NAME, 
        WEEK, DAY, DAY_OF_WEEK, DAY_NAME, IS_WEEKEND, IS_HOLIDAY
    )
    SELECT
        TO_NUMBER(TO_CHAR(date_val, 'YYYYMMDD')) AS DATE_KEY,
        date_val AS DATE_VALUE,
        YEAR(date_val) AS YEAR,
        QUARTER(date_val) AS QUARTER,
        MONTH(date_val) AS MONTH,
        TO_CHAR(date_val, 'MMMM') AS MONTH_NAME,
        WEEKOFYEAR(date_val) AS WEEK,
        DAY(date_val) AS DAY,
        DAYOFWEEK(date_val) AS DAY_OF_WEEK,
        TO_CHAR(date_val, 'DY') AS DAY_NAME,
        CASE WHEN DAYOFWEEK(date_val) IN (0, 6) THEN TRUE ELSE FALSE END AS IS_WEEKEND,
        FALSE AS IS_HOLIDAY
    FROM (
        SELECT DATEADD(day, SEQ4(), '2023-01-01'::DATE) AS date_val
        FROM TABLE(GENERATOR(ROWCOUNT => 1461))  -- 4 years = 1461 days
    )
    WHERE date_val <= '2026-12-31'
    AND NOT EXISTS (
        SELECT 1 FROM ELECTRICITY_ANALYTICS.DIM_DATE 
        WHERE DATE_VALUE = date_val
    );
    
    RETURN 'DIM_DATE populated successfully';
END;
$$;

-- Execute the procedure
CALL ELECTRICITY_ANALYTICS.POPULATE_DIM_DATE();

-- ============================================
-- Verification Queries
-- ============================================
SELECT 'ELECTRICITY_RAW tables' AS SCHEMA_NAME, COUNT(*) AS TABLE_COUNT 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'ELECTRICITY_RAW';

SELECT 'ELECTRICITY_STAGING tables' AS SCHEMA_NAME, COUNT(*) AS TABLE_COUNT 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'ELECTRICITY_STAGING';

SELECT 'ELECTRICITY_ANALYTICS tables' AS SCHEMA_NAME, COUNT(*) AS TABLE_COUNT 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'ELECTRICITY_ANALYTICS';

SELECT 'ELECTRICITY_ML tables' AS SCHEMA_NAME, COUNT(*) AS TABLE_COUNT 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'ELECTRICITY_ML';

-- Check dimension data
SELECT 'DIM_REGION records' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT 
FROM ELECTRICITY_ANALYTICS.DIM_REGION;

SELECT 'DIM_DATE records' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT 
FROM ELECTRICITY_ANALYTICS.DIM_DATE;

-- ============================================
-- Grant Permissions (for Tableau read-only user)
-- ============================================
-- Run these after creating a Tableau service account
-- CREATE USER tableau_reader PASSWORD='SecurePassword123!';
-- GRANT USAGE ON DATABASE USER_DB_HIPPO TO ROLE tableau_reader;
-- GRANT USAGE ON SCHEMA ELECTRICITY_ANALYTICS TO ROLE tableau_reader;
-- GRANT SELECT ON ALL TABLES IN SCHEMA ELECTRICITY_ANALYTICS TO ROLE tableau_reader;
-- GRANT SELECT ON FUTURE TABLES IN SCHEMA ELECTRICITY_ANALYTICS TO ROLE tableau_reader;
