-- ============================================
-- INITIAL SNOWFLAKE SETUP
-- Run this ONCE in Snowflake UI before starting Airflow
-- ============================================

USE DATABASE USER_DB_HIPPO;

-- ============================================
-- STEP 1: CREATE SCHEMAS
-- ============================================
CREATE SCHEMA IF NOT EXISTS ELECTRICITY_RAW;
CREATE SCHEMA IF NOT EXISTS ELECTRICITY_STAGING;
CREATE SCHEMA IF NOT EXISTS ELECTRICITY_ANALYTICS;
CREATE SCHEMA IF NOT EXISTS ELECTRICITY_ML;

-- ============================================
-- STEP 2: CREATE RAW TABLES
-- ============================================
DROP TABLE IF EXISTS ELECTRICITY_RAW.EIA_HOURLY_DEMAND;
CREATE TABLE ELECTRICITY_RAW.EIA_HOURLY_DEMAND (
    PERIOD_DATE TIMESTAMP NOT NULL,
    RESPONDENT VARCHAR(50) NOT NULL,
    RESPONDENT_NAME VARCHAR(255),
    DATA_TYPE VARCHAR(20) NOT NULL,
    DATA_TYPE_NAME VARCHAR(255),
    VALUE FLOAT,
    VALUE_UNITS VARCHAR(50),
    LOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (PERIOD_DATE, RESPONDENT, DATA_TYPE)
);

-- Temp/staging table for ETL process
DROP TABLE IF EXISTS ELECTRICITY_RAW.EIA_HOURLY_DEMAND_TEMP;
CREATE TABLE ELECTRICITY_RAW.EIA_HOURLY_DEMAND_TEMP (
    PERIOD_DATE TIMESTAMP NOT NULL,
    RESPONDENT VARCHAR(50) NOT NULL,
    RESPONDENT_NAME VARCHAR(255),
    DATA_TYPE VARCHAR(20) NOT NULL,
    DATA_TYPE_NAME VARCHAR(255),
    VALUE FLOAT,
    VALUE_UNITS VARCHAR(50)
);

-- ============================================
-- STEP 3: CREATE STAGING TABLES
-- ============================================
DROP TABLE IF EXISTS ELECTRICITY_STAGING.STG_EIA_HOURLY_DEMAND;
CREATE TABLE ELECTRICITY_STAGING.STG_EIA_HOURLY_DEMAND (
    PERIOD_DATE TIMESTAMP NOT NULL,
    RESPONDENT VARCHAR(50) NOT NULL,
    RESPONDENT_NAME VARCHAR(255),
    DATA_TYPE VARCHAR(20) NOT NULL,
    DATA_TYPE_NAME VARCHAR(255),
    VALUE FLOAT,
    VALUE_UNITS VARCHAR(50),
    LOADED_AT TIMESTAMP,
    PRIMARY KEY (PERIOD_DATE, RESPONDENT, DATA_TYPE)
);

DROP TABLE IF EXISTS ELECTRICITY_STAGING.STG_DEMAND_BY_REGION;
CREATE TABLE ELECTRICITY_STAGING.STG_DEMAND_BY_REGION (
    PERIOD_DATE TIMESTAMP NOT NULL,
    RESPONDENT VARCHAR(50) NOT NULL,
    RESPONDENT_NAME VARCHAR(255),
    TOTAL_DEMAND FLOAT,
    AVG_DEMAND FLOAT,
    MAX_DEMAND FLOAT,
    MIN_DEMAND FLOAT,
    RECORD_COUNT INT,
    PRIMARY KEY (PERIOD_DATE, RESPONDENT)
);

-- ============================================
-- STEP 4: CREATE ANALYTICS TABLES
-- ============================================
DROP TABLE IF EXISTS ELECTRICITY_ANALYTICS.DIM_REGION;
CREATE TABLE ELECTRICITY_ANALYTICS.DIM_REGION (
    REGION_KEY INT AUTOINCREMENT PRIMARY KEY,
    RESPONDENT VARCHAR(50) UNIQUE NOT NULL,
    RESPONDENT_NAME VARCHAR(255),
    REGION_TYPE VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

DROP TABLE IF EXISTS ELECTRICITY_ANALYTICS.DIM_DATE;
CREATE TABLE ELECTRICITY_ANALYTICS.DIM_DATE (
    DATE_KEY INT PRIMARY KEY,
    DATE_VALUE DATE NOT NULL,
    YEAR INT,
    QUARTER INT,
    MONTH INT,
    MONTH_NAME VARCHAR(20),
    WEEK INT,
    DAY INT,
    DAY_OF_WEEK INT,
    DAY_NAME VARCHAR(20),
    IS_WEEKEND BOOLEAN,
    IS_HOLIDAY BOOLEAN
);

DROP TABLE IF EXISTS ELECTRICITY_ANALYTICS.FCT_HOURLY_DEMAND;
CREATE TABLE ELECTRICITY_ANALYTICS.FCT_HOURLY_DEMAND (
    DEMAND_KEY INT AUTOINCREMENT PRIMARY KEY,
    PERIOD_DATE TIMESTAMP NOT NULL,
    DATE_KEY INT,
    REGION_KEY INT,
    HOUR INT,
    DEMAND_VALUE FLOAT,
    DEMAND_UNITS VARCHAR(50),
    LOADED_AT TIMESTAMP
);

DROP TABLE IF EXISTS ELECTRICITY_ANALYTICS.ANALYTICS_DEMAND_SUMMARY;
CREATE TABLE ELECTRICITY_ANALYTICS.ANALYTICS_DEMAND_SUMMARY (
    SUMMARY_KEY INT AUTOINCREMENT PRIMARY KEY,
    PERIOD_DATE TIMESTAMP NOT NULL,
    REGION VARCHAR(50),
    HOUR INT,
    DAY_OF_WEEK INT,
    TOTAL_DEMAND FLOAT,
    AVG_DEMAND FLOAT,
    MAX_DEMAND FLOAT,
    MIN_DEMAND FLOAT,
    DEMAND_VARIANCE FLOAT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================
-- STEP 5: CREATE ML TABLES
-- ============================================
DROP TABLE IF EXISTS ELECTRICITY_ML.FORECAST_RESULTS;
CREATE TABLE ELECTRICITY_ML.FORECAST_RESULTS (
    FORECAST_KEY INT AUTOINCREMENT PRIMARY KEY,
    FORECAST_DATE TIMESTAMP NOT NULL,
    REGION VARCHAR(50) NOT NULL,
    FORECAST_HORIZON INT,
    PREDICTED_DEMAND FLOAT,
    ACTUAL_DEMAND FLOAT,
    PREDICTION_ERROR FLOAT,
    MODEL_VERSION VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

DROP TABLE IF EXISTS ELECTRICITY_ML.MODEL_METRICS;
CREATE TABLE ELECTRICITY_ML.MODEL_METRICS (
    METRIC_KEY INT AUTOINCREMENT PRIMARY KEY,
    MODEL_VERSION VARCHAR(50) NOT NULL,
    TRAINING_DATE TIMESTAMP NOT NULL,
    REGION VARCHAR(50),
    METRIC_NAME VARCHAR(50),
    METRIC_VALUE FLOAT,
    DATASET_TYPE VARCHAR(20),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

DROP TABLE IF EXISTS ELECTRICITY_ML.FEATURE_IMPORTANCE;
CREATE TABLE ELECTRICITY_ML.FEATURE_IMPORTANCE (
    FEATURE_KEY INT AUTOINCREMENT PRIMARY KEY,
    MODEL_VERSION VARCHAR(50) NOT NULL,
    FEATURE_NAME VARCHAR(100),
    IMPORTANCE_SCORE FLOAT,
    RANK INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================
-- STEP 6: POPULATE DIM_REGION (6 regions)
-- ============================================
INSERT INTO ELECTRICITY_ANALYTICS.DIM_REGION (RESPONDENT, RESPONDENT_NAME, REGION_TYPE)
SELECT 'US48', 'United States Lower 48', 'National'
WHERE NOT EXISTS (SELECT 1 FROM ELECTRICITY_ANALYTICS.DIM_REGION WHERE RESPONDENT = 'US48');

INSERT INTO ELECTRICITY_ANALYTICS.DIM_REGION (RESPONDENT, RESPONDENT_NAME, REGION_TYPE)
SELECT 'CISO', 'California Independent System Operator', 'Regional'
WHERE NOT EXISTS (SELECT 1 FROM ELECTRICITY_ANALYTICS.DIM_REGION WHERE RESPONDENT = 'CISO');

INSERT INTO ELECTRICITY_ANALYTICS.DIM_REGION (RESPONDENT, RESPONDENT_NAME, REGION_TYPE)
SELECT 'TEXA', 'Electric Reliability Council of Texas', 'Regional'
WHERE NOT EXISTS (SELECT 1 FROM ELECTRICITY_ANALYTICS.DIM_REGION WHERE RESPONDENT = 'TEXA');

INSERT INTO ELECTRICITY_ANALYTICS.DIM_REGION (RESPONDENT, RESPONDENT_NAME, REGION_TYPE)
SELECT 'MISO', 'Midcontinent Independent System Operator', 'Regional'
WHERE NOT EXISTS (SELECT 1 FROM ELECTRICITY_ANALYTICS.DIM_REGION WHERE RESPONDENT = 'MISO');

INSERT INTO ELECTRICITY_ANALYTICS.DIM_REGION (RESPONDENT, RESPONDENT_NAME, REGION_TYPE)
SELECT 'NYISO', 'New York Independent System Operator', 'Regional'
WHERE NOT EXISTS (SELECT 1 FROM ELECTRICITY_ANALYTICS.DIM_REGION WHERE RESPONDENT = 'NYISO');

INSERT INTO ELECTRICITY_ANALYTICS.DIM_REGION (RESPONDENT, RESPONDENT_NAME, REGION_TYPE)
SELECT 'PJM', 'PJM Interconnection', 'Regional'
WHERE NOT EXISTS (SELECT 1 FROM ELECTRICITY_ANALYTICS.DIM_REGION WHERE RESPONDENT = 'PJM');

-- ============================================
-- STEP 7: POPULATE DIM_DATE (2023-2026)
-- ============================================
INSERT INTO ELECTRICITY_ANALYTICS.DIM_DATE (
    DATE_KEY, DATE_VALUE, YEAR, QUARTER, MONTH, MONTH_NAME, 
    WEEK, DAY, DAY_OF_WEEK, DAY_NAME, IS_WEEKEND, IS_HOLIDAY
)
SELECT
    TO_NUMBER(TO_CHAR(date_val, 'YYYYMMDD')) AS DATE_KEY,
    date_val AS DATE_VALUE,
    YEAR(date_val) AS YEAR,
    QUARTER(date_val) AS QUARTER,
    MONTH(date_val) AS MONTH,
    TO_CHAR(date_val, 'MMMM') AS MONTH_NAME,
    WEEKOFYEAR(date_val) AS WEEK,
    DAY(date_val) AS DAY,
    DAYOFWEEK(date_val) AS DAY_OF_WEEK,
    TO_CHAR(date_val, 'DY') AS DAY_NAME,
    CASE WHEN DAYOFWEEK(date_val) IN (0, 6) THEN TRUE ELSE FALSE END AS IS_WEEKEND,
    FALSE AS IS_HOLIDAY
FROM (
    SELECT DATEADD(day, SEQ4(), '2023-01-01'::DATE) AS date_val
    FROM TABLE(GENERATOR(ROWCOUNT => 1461))
)
WHERE date_val <= '2026-12-31'
AND NOT EXISTS (
    SELECT 1 FROM ELECTRICITY_ANALYTICS.DIM_DATE 
    WHERE DATE_VALUE = date_val
);

-- ============================================
-- STEP 8: VERIFICATION
-- ============================================
-- Check schemas (should return 4)
SELECT COUNT(*) AS SCHEMA_COUNT 
FROM INFORMATION_SCHEMA.SCHEMATA 
WHERE SCHEMA_NAME LIKE 'ELECTRICITY%';

-- Check tables per schema
SELECT TABLE_SCHEMA, COUNT(*) AS TABLE_COUNT
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA LIKE 'ELECTRICITY%'
GROUP BY TABLE_SCHEMA
ORDER BY TABLE_SCHEMA;

-- Check DIM_REGION (should return 6)
SELECT COUNT(*) AS REGION_COUNT FROM ELECTRICITY_ANALYTICS.DIM_REGION;

-- Check DIM_DATE (should return 1461)
SELECT COUNT(*) AS DATE_COUNT FROM ELECTRICITY_ANALYTICS.DIM_DATE;

-- View regions
SELECT * FROM ELECTRICITY_ANALYTICS.DIM_REGION ORDER BY REGION_KEY;

-- View sample dates
SELECT * FROM ELECTRICITY_ANALYTICS.DIM_DATE ORDER BY DATE_VALUE LIMIT 10;

-- ============================================
-- SETUP COMPLETE!
-- ============================================
-- Next steps:
-- 1. Go to Airflow UI (http://localhost:8081)
-- 2. Configure Snowflake connection (Admin → Connections)
-- 3. Add EIA API key variable (Admin → Variables)
-- 4. Enable and trigger: electricity_eia_etl_live
-- ============================================
